services:
  - type: web
    name: bookstore-app
    env: python
    pythonVersion: "3.11.0"
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 2 --worker-class sync --timeout 60 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
